FROM node:latest


WORKDIR /app

COPY package*.json ./

ENV ON_PROVER_ACCESS_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiYWFjNGZmMmYtNWYwMC00MDFlLTg4NDktMTdkYzgwZDUxNzU2IiwidXNlcm5hbWUiOiIweDJmMThmMzZhZjg1NzQ1NWVjNjE2MzNjNjVjYjJmMmNlYWI2YmZiZTYiLCJpZCI6IjI5NTYwNSIsImJhblVudGlsIjpudWxsLCJzaWQiOiI4ZTg1Y2MyNC0wM2MwLTRhMzEtOTk3MC04YmNlZmU2YzhmMDQiLCJleHAiOjE3NTcxNjgxNDV9.IxxNInlOT7YJ3cRDDtOSy65hqHmwpLF_CGEJAL9npyM"


RUN npm install
COPY . .


CMD [ "node", "app.js" ]