FROM node:latest


WORKDIR /app

COPY package*.json ./

ENV ON_PROVER_ACCESS_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiNjI1YzM5YTAtM2UwMy00ZjYxLTlmNDMtMjdkNmFlODU5MGFhIiwidXNlcm5hbWUiOiIweDRkYmZlNzhiMWUwNTQ1NmM3N2Y5MDQ4ZGNhZWJiODVjZDk2NjY1MmUiLCJpZCI6IjEyNDg0MCIsImJhblVudGlsIjpudWxsLCJzaWQiOiI1Yzk2NzJjNC0yZTk2LTQ3ZTAtYjNlNy0yMzRhMTcyNjMyYzgiLCJleHAiOjE3NTYwMjA5OTd9.mkNSBrRhyIq8sl7cHjHkWmbNcLNZmsJheKAem6_ib9E"


RUN npm install
COPY . .


CMD [ "node", "slenium.js" ]